# Generated by Django 3.1.6 on 2021-02-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210218_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='likes', to='network.Post'),
        ),
    ]
